CREATE TABLE tarefa (
    id BIGINT NOT NULL AUTO_INCREMENT,
    titulo VARCHAR(255) NOT NULL,
    descricao VARCHAR(255) NOT NULL,
    local VARCHAR(255) NOT NULL,
    data_hora DATETIME NOT NULL,
    PRIMARY KEY (id)
);
